hide boosts findboost and use cmakes

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -43,21 +43,21 @@ jobs:
 
       - name: Install Boost on macOS
         if: runner.os == 'macOS'
-        run: brew install boost
+        run: brew install boost && rm -rf /usr/local/lib/cmake/Boost-* || true
 
-      - name: Inspect Boost installation
-        if: runner.os == 'macOS'
-        run: |
-          echo "==== BoostConfig.cmake content ===="
-          cat /usr/local/lib/cmake/Boost-1.89.0/BoostConfig.cmake || echo "BoostConfig.cmake not found"
+      # - name: Inspect Boost installation
+      #   if: runner.os == 'macOS'
+      #   run: |
+      #     echo "==== BoostConfig.cmake content ===="
+      #     cat /usr/local/lib/cmake/Boost-1.89.0/BoostConfig.cmake || echo "BoostConfig.cmake not found"
 
-          echo ""
-          echo "==== Searching for boost_systemConfig.cmake or boost_system-config.cmake ===="
-          find /usr/local -type f \( -name "boost_systemConfig.cmake" -o -name "boost_system-config.cmake" \) || echo "No per-component BoostConfig found"
+      #     echo ""
+      #     echo "==== Searching for boost_systemConfig.cmake or boost_system-config.cmake ===="
+      #     find /usr/local -type f \( -name "boost_systemConfig.cmake" -o -name "boost_system-config.cmake" \) || echo "No per-component BoostConfig found"
 
-          echo "==== /usr/local/lib/cmake/Boost-1.89.0/ directory tree ===="
-          brew install tree || true
-          tree /usr/local/lib/cmake/Boost-1.89.0 || echo "Directory not found"
+      #     echo "==== /usr/local/lib/cmake/Boost-1.89.0/ directory tree ===="
+      #     brew install tree || true
+      #     tree /usr/local/lib/cmake/Boost-1.89.0 || echo "Directory not found"
 
       - name: Build wheels
         uses: pypa/cibuildwheel@v3.2.1
